---
description: error handing
---

# 3.1 错误处理

rust中的错误处理机制：

```rust
// panic抛出错误, 用于不可恢复错误处理
panic!("xx");  // panic会使程序终止
```

## Option类型

Option<T>枚举用于存在和不存在情况处理。

```rust
// Option<T>枚举类型
fn match_option(val: Option<&str>) {  // 使用match模式处理
    match val {
        Some("xx") => println!("xx"),  // 找到属于T类型的元素
        None => println!("no"),  // 找不到相应元素
    }
}

// 使用unwrap处理Option
fn unwrap_option(val: Option<&str>) {
    let result = val.unwrap();  // unwrap接收到None时将返回panic
    if result == "other" { panic!("xx"); }  // 其它场景处理
}

// 使用？解开Option
struct Person { job: Option<Job>, }
struct Job { phone: Option<Num>, }
struct Num { code: Option<u8>, num: u32, }
impl Person {
    fn get_phone(&self) -> Option<u8> {
        self.job?.phone?.code  // 当?后的值时None时返回None, 否则返回Some底层值
    }  // 使用?可有效避免多层match嵌套
}

// 组合算子map, map()是Option的内置方法, 用于Some -> Some和None -> None的映射
enum Food { Apple, Potato, Sushi }
struct Peeled(Food);
struct Cooked(Food);
fn process(food: Option<Food>) -> Option<Cooked> {
    food.map(|f| Peeled(f))
        .map(|Peeled(f)| Cooked(f))
}

// 组合算子and_then, and_then()使用被Option包裹的值来调用其输入函数并返回结果
fn have_raw(food: Food) -> Option<Food> {
    match food {
        Food::Apple => None,
        _ => Some(food),
    }
}
fn have_list(food: Food) -> Option<Food> {
    match food {
        Food::Sushi => None,
        _ => Some(food),
    }
}
fn cookable(food: Food) -> Option<Food> {
    have_raw(food).and_then(have_list)  // 将have_raw结果作为have_list参数
}
```

## Result类型

Result<T, E>类型用于可恢复错误场景。

```rust
// Result<T, E>有两种结果: Ok<T>符合预期, Err<E>不符合预期
fn (a: &str) -> Result<i32, ParseIntError> {
    match a.parse::<i32>() {
        OK(n) => return Ok(n),
        Err(e) => return Err(e),
    }
}

// 使用unwrap处理Result
fn parse_str(val: &str) -> i32 {
    val.parse::<i32>().unwrap()  // 错误时将返回panic
    // val.parse::<i32>().expect("parse error")  自定义错误信息 
}

// Result的map(), and_then组合算子
fn muli(a: &str, b: &str) -> Result<i32, ParseIntError> {
    a.parse::<i32>().and_then(|a| {
        b.parse::<i32>().map(|b| a * b)
    })
}

// 使用?运算符
fn muli(a: &str, b: &str) -> Result<i32, ParseIntError> {
    let a = a.parse::<i32>()?;  // 当为Err时会直接返回Err
    let b = b.parse::<i32>()?;
    Ok(a * b)
}

// try!宏, 功能与?类似, 在一些老代码中会使用
fn test(a: &str) -> Result<i32, ParseIntError> {
    let a = try!(a.parse::<i32>()); ok(a)
}

// Result别名
type MyResult<T> = Result<T, ParseIntError>;

// Option和Result混合使用
fn vec_one(val: Vec<&str>) -> Option<Result<i32, ParseIntError>> {
    val.first().map(|a| { a.parse::<i32>().map(|n| 2 * n) })
}
fn vec_two(val: Vec<&str>) -> Result<Option<i32, ParseIntError>> {
    let opt = val.first().map(|a| { a.parse::<i32>().map(|n| 2 * n) });
    opt.map_or(Ok(None), |r| r.map(Some))
}

// 遍历Result, 过滤失败项
let num: Vec<_> = vals.into_iter().filter_map(|s| s.parse::<i32>().ok()).collect();

// 遍历Result, 失败时终止遍历
let num: Result<Vec<_>, _> = vals.into_iter().map(|s| s.parse::<i32>()).collect();

// 遍历Result, 分开收集合法值和错误
let (num, errs): (Vec<_>, Vec<_>) = vals.into_iter()
                                        .map(|s| s.parse::<i32>())
                                        .partition(Result::is_ok);
let num: Vec<_> = num.into_iter().map(Result::unwrap).collect();  // 提取合法值
let errs: Vec<_> = errs.into_iter().map(Result::unwrap_err).collect();  /// 提取错误
```

## 自定义错误类型

rust自定义错误类型格式：

```rust
use std::{error, fmt};  // 引用标准库

#[derive(Debug, Clone)]  // 自定义错误类型
struct MyError;
impl fmt::Display for MyError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "error information")  // 错误描述
    }
}
impl error::Error for MyError {  // 实现Error trait
    fn source(&self) -> Option<&(dyn error::Error + 'static)> { None }
}
type Result<i32> = std::result::Result<T, MyError>;  // 包装自定义类型

// 自定义错误使用
fn parse_str(val: Vec<&str>) -> Result<i32> {
    val.first().ok_or(MyError)  // 转换为自定义错误类型
        .and_then(|s| { s.parse::<i32>().map_err(|_| MyError)  // 转换为自定义错误
        .map(|i| 2 * i)
    })
}

// 使用?, 在错误可转换成返回类型的地方, 自动转换返回类型
fn parse_str(val: Vec<&str>) -> Result<i32> {
    let first = val.first().ok_or(MyError)?;  // 自动转换返回类型
    let res = first.parse::<i32>()?;  // 省略map_err
    Ok(2 * res)
}

// 使用Box包装
type Result<T> = std::result::Result<T, Box<dyn error::Error>>;

// 包裹错误
enum MyError { EmptyVec, Parse(ParseIntError), }
```

